interface=br-router
bind-interfaces
except-interface=lo
dhcp-range=10.42.0.50,10.42.0.200,255.255.255.0,12h
dhcp-option=3,10.42.0.1
dhcp-option=6,10.42.0.1
server=1.1.1.1
server=8.8.8.8
domain-needed
bogus-priv
dhcp-host=04:42:1a:85:9b:80,10.42.0.200
dhcp-host=92:25:3d:52:12:2f,10.42.0.220
dhcp-host=dc:04:5a:f5:f6:e0,10.42.0.221
dhcp-host=dc:32:62:12:ec:20,10.42.0.222
dhcp-leasefile=/home/solumate/code/router/state/dnsmasq.leases
pid-file=/home/solumate/code/router/state/dnsmasq.pid
log-dhcp
