base {
  log_debug = off;
  log_info = on;
  log = stderr;
  daemon = on;
  redirector = iptables;
}

redsocks {
  local_ip = 10.42.0.1;
  local_port = 23450;
  ip = 200.229.24.170;
  port = 25148;
  type = http-connect;
  login = "YufMaX";
  password = "WJamao";
}

redsocks {
  local_ip = 10.42.0.1;
  local_port = 23451;
  ip = 23.95.159.84;
  port = 39703;
  type = http-connect;
  login = "fxrNco";
  password = "mxRytb";
}

redsocks {
  local_ip = 10.42.0.1;
  local_port = 23452;
  ip = 89.106.0.176;
  port = 25497;
  type = http-connect;
  login = "jNfGcK";
  password = "rThhwH";
}

redsocks {
  local_ip = 10.42.0.1;
  local_port = 23453;
  ip = 206.125.175.208;
  port = 28367;
  type = socks5;
  login = "DlnaEv";
  password = "Qlfcub";
}

redsocks {
  local_ip = 10.42.0.1;
  local_port = 23454;
  ip = 206.125.175.117;
  port = 20217;
  type = socks5;
  login = "PYiGvc";
  password = "YZunKT";
}

redsocks {
  local_ip = 10.42.0.1;
  local_port = 23455;
  ip = 160.30.190.150;
  port = 23102;
  type = socks5;
  login = "nKivAB";
  password = "zyfZfJ";
}
