base {
  log_debug = off;
  log_info = on;
  log = stderr;
  daemon = on;
  redirector = iptables;
}

redsocks {
  local_ip = 10.42.0.1;
  local_port = 23450;
  ip = 103.82.39.178;
  port = 53031;
  type = http-connect;
  login = "0799640848";
  password = "0799640848";
}
